repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=88]
        
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: [--profile=black]
        
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [--max-line-length=88]
        
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--show-error-codes]
        files: ^src/
        
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        args: [tests/, -v, --cov=src/persephone]
        pass_filenames: false
        always_run: true